-- MySQL Script generated by MySQL Workbench
-- Fri Nov 26 16:16:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Person` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
   `id` INT NOT NULL AUTO_INCREMENT,
   `first_name` VARCHAR(45) NOT NULL,
   `last_name` VARCHAR(45) NOT NULL,
   `login_id` INT NOT NULL,
   `bank_id` INT NOT NULL,
   PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction_Internal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Transaction_Internal` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Transaction_Internal` (
     `id` INT NOT NULL AUTO_INCREMENT,
     `description` TEXT(100) NULL,
     `amount` DECIMAL(18,2) NULL,
     `time_transaction` DATETIME NULL,
     `crediteur_id` INT NOT NULL,
     `debiteur_id` INT NOT NULL,
     PRIMARY KEY (`id`),
     INDEX `fk_crediteur_id_person_idx` (`crediteur_id` ASC) VISIBLE,
     INDEX `fk_crediteur_id_person_idx1` (`debiteur_id` ASC) VISIBLE,
     CONSTRAINT `fk_crediteur_id_person`
         FOREIGN KEY (`crediteur_id`)
             REFERENCES `mydb`.`Person` (`id`)
             ON DELETE NO ACTION
             ON UPDATE NO ACTION,
     CONSTRAINT `fk_dediteur_id_person`
         FOREIGN KEY (`debiteur_id`)
             REFERENCES `mydb`.`Person` (`id`)
             ON DELETE NO ACTION
             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`login` ;

--   `user_id` INT NOT NULL,
CREATE TABLE IF NOT EXISTS `mydb`.`login` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(100) NOT NULL,
    `password` VARCHAR(100) NOT NULL,
    `person_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `email_unique_id` (`email` ASC) INVISIBLE,
    INDEX `fk_user_id_person_id_idx` (`id` ASC) VISIBLE,
    CONSTRAINT `fk_user_id_person_id`
      FOREIGN KEY (`person_id`)
          REFERENCES `mydb`.`Person` (`id`)
          ON DELETE NO ACTION
          ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bank` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bank` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `iban` VARCHAR(45) NOT NULL,
    `amount` DECIMAL(18,2) NULL,
    `person_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_bank_id_person_id_idx` (`person_id` ASC) VISIBLE,
    UNIQUE INDEX `Iban_unique_id` (`iban` ASC) INVISIBLE,
    CONSTRAINT `fk_bank_id_person_id`
        FOREIGN KEY (`person_id`)
            REFERENCES `mydb`.`Person` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`commission` ;

CREATE TABLE IF NOT EXISTS `mydb`.`commission` (
   `id` INT NOT NULL AUTO_INCREMENT,
   `transaction_id` INT NOT NULL,
   `amount` DECIMAL(18,2) NULL,
   PRIMARY KEY (`id`),
   INDEX `fk_transaction_id_crediteur_id_idx` (`transaction_id` ASC) VISIBLE,
   CONSTRAINT `fk_transaction_id_crediteur_id`
       FOREIGN KEY (`transaction_id`)
           REFERENCES `mydb`.`Transaction_Internal` (`id`)
           ON DELETE NO ACTION
           ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Social_Networks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`social_networks` ;

--   `id_commission` INT NOT NULL,
--   PRIMARY KEY (`id_commission`),
CREATE TABLE IF NOT EXISTS `mydb`.`social_networks` (
    `this_person` INT NOT NULL,
    `is_related_to` INT NOT NULL,
    INDEX `fk_this_person_id_idx` (`this_person` ASC) VISIBLE,
    INDEX `fk_is_related_to_id_idx` (`is_related_to` ASC) VISIBLE,
    CONSTRAINT `fk_this_person_id`
        FOREIGN KEY (`this_person`)
            REFERENCES `mydb`.`Person` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_is_related_to_id`
        FOREIGN KEY (`is_related_to`)
            REFERENCES `mydb`.`Person` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction_External`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Transaction_External` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Transaction_External` (
     `id` INT NOT NULL,
     `user_id` INT NOT NULL,
     `amount` DECIMAL(18,2) NULL,
     `time_transaction` DATETIME NULL,
     `description` TEXT(100) NULL,
     PRIMARY KEY (`id`),
     INDEX `fk_transactionex_id_person_idx` (`user_id` ASC) VISIBLE,
     CONSTRAINT `fk_transactionex_id_person`
         FOREIGN KEY (`user_id`)
             REFERENCES `mydb`.`Person` (`id`)
             ON DELETE NO ACTION
             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
